### PR TITLE
Fix introspection and apply formatting fixes

### LINKED ISSUE #45: ObjectType inheritance issues
I'm attempting to do codegen for frontend code using graphql introspection, but having some issues. The root of my problems seem to be that `GraphQL::Field` annotations aren't inherited by extending types.

This means that if I have a `PaginatedOutcome` class containing `total_count`, `total_pages`, and `has_more` fields and then I attempt to extend that object with `UsersPaginatedOutcome` which adds the `users` field, all that is seen by introspection is the `users` field which breaks codegen. It also makes it so that utilities like Postman don't work in these cases because they rely on introspection to make sure the fields are correct.

### PR DESCRIPTION
**Pull request by watzon**
Closes #45

### CODE REVIEW

**Comment by watzon** [comment]
Looks like it's just failing because of Ameba issues that were there before I made any changes

**Comment by jgillich** [comment]
Looks good, thanks. The Ameba problems seem to be fixed in the master version, if you don't mind, could you try adding `branch: master` to the shard.yml?

**Comment by watzon** [comment]
@jgillich you mean the master branch for ameba?

**Comment by jgillich** [comment]
Yes.

**Comment by watzon** [comment]
Doesn't seem to fix the problems for me since most are `not_nil!` issues, but I'll do it and push anyway

**Comment by jgillich** [comment]
I'd do it myself but my devcontainer doesn't want to start right now and I'm not sure why 🤔

**Comment by watzon** [comment]
Looks like we're good!

**Comment by jgillich** [comment]
Thanks

**Pull request merged**
